### ISSUE TITLE
Any plans on separating the theme from the actual blog?

### ISSUE THREAD

**Issue by arunanshub** [xypnox/xyblag-theme#1]
First of all, thank you for this excellent theme 👍🏼. It is both visually appealing and accessible.

Currently, the `xyblag` theme resides in [themes/xyblag](https://github.com/xypnox/blag/tree/master/themes/xyblag), which makes it difficult to use it as a submodule.

I'd be great if you could migrate the `xyblag` theme here.

**Comment by xypnox** [comment]
Hi, I don't have a plan to migrate the theme here.

Currently, I don't have the bandwidth to make each personal customization as an option for the user. For example, the commenting system: I switched from disqus to utterances, and I can make such breaking changes quickly if I don't also have to maintain them for everyone. 


Though I agree that there should be themes that allow people to start blogging quickly with minimal setup and all bells and whistles, I don't think this theme would be one of them. If someone is interested in maintaining it as a proper theme that people can just pick and use, I am supportive of it, just that I don't have time to devote to it. I want people to take the theme from the blog and customize it, bend it to their personality and blogging style, not just copy and make another generic blog.

In it's current state the theme serves as a boilerplate to develop a custom theme on, with all pages for blog, about, tags, categories etc setup and a decent css layout to customize.
